### ISSUE TITLE
I couldn't get it to work

### ISSUE THREAD

**Issue by 667Labs** [PROTechThor/Blobby#4]
I can't create a new character, can you explain in detail please?

**Comment by enjeck** [comment]
@667Labs You mean you can't run it locally?

**Comment by 667Labs** [comment]
> 

Yes.

i'm doing all the necessary setups, unfortunately I couldn't create an image

**Comment by 667Labs** [comment]
Traceback (most recent call last):
  File "C:\Users\Eray\Desktop\Blobby-master\app.py", line 4, in <module>
    from cairosvg import svg2png
  File "C:\Users\Eray\AppData\Local\Programs\Python\Python39\lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Users\Eray\AppData\Local\Programs\Python\Python39\lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\Users\Eray\AppData\Local\Programs\Python\Python39\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Users\Eray\AppData\Local\Programs\Python\Python39\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

**Comment by enjeck** [comment]
@667Labs The error message shows your problem, I think. You have to install the Cairo library. Install every library listed here (except for gunicorn): https://github.com/enjeck/Blobby/blob/master/requirements.txt

**Comment by 667Labs** [comment]
I installed all of them completely, unfortunately I get the same error.

**Comment by enjeck** [comment]
@667Labs I have no idea how to fix this now. If I ever figure out a solution, I'll let you know.

**Comment by in1yan** [comment]
Download and install cairo dev environment
https://gladewin32.sourceforge.net/
